Tropo Documentation: https://www.tropo.com/docs/
Twilio Documentation: https://www.twilio.com/api
mashape APIS: https://www.mashape.com/
http://www.programmableweb.com/news/6-new-apis-track-billing-patent-search-phone-number-lookup-domains-and-photos/2010/05/08
Whitepage: http://pro.whitepages.com/features/api-overview/
Python fetch: https://docs.python.org/3/howto/urllib2.html
Twilio APIS: https://www.twilio.com/docs/api/rest
Scrape pages from website: http://code.tutsplus.com/tutorials/how-to-scrape-web-pages-with-nodejs-and-jquery--net-22478

