Tropo Documentation: https://www.tropo.com/docs/
Twilio Documentation: https://www.twilio.com/api
mashape APIS: https://www.mashape.com/
http://www.programmableweb.com/news/6-new-apis-track-billing-patent-search-phone-number-lookup-domains-and-photos/2010/05/08
Whitepage: http://pro.whitepages.com/features/api-overview/
Python fetch: https://docs.python.org/3/howto/urllib2.html
Twilio APIS: https://www.twilio.com/docs/api/rest
Scrape pages from website: http://code.tutsplus.com/tutorials/how-to-scrape-web-pages-with-nodejs-and-jquery--net-22478
Twilio python helper: https://www.twilio.com/docs/python/install
https://www.twilio.com/blog/2013/08/verify-phone-numbers-with-node-js-using-twilio-sms-express-and-socket-io.html
http://www.sitepoint.com/working-phone-numbers-javascript/
好 那个题我觉得实质是用python写一个爬虫cralwer 可以用到的库有urllib2和beautifulsoup 你可以看看github上有好多类似的cralwer代码
Python module: urllib2, BeautifulSoup
http://www.w3school.com.cn/tags/att_a_href.asp
http://www.crummy.com/software/BeautifulSoup/bs4/doc/#searching-the-tree
正则表达式：http://www.cnblogs.com/huxi/archive/2010/07/04/1771073.html
一个简单java爬虫爬取网页中邮箱并保存： http://blog.csdn.net/u013018721/article/details/36929579
利用python的webscraping库采集抓取爱帮网电话号码：http://www.jincon.com/tag/webscraping/
scrape the page, Using Python Beautiful Soup: http://kochi-coders.com/2011/05/30/lets-scrape-the-page-using-python-beautifulsoup/
Extract Href Links (Urls) From HTML Using Regular Expression in Python: http://incurlybraces.com/extract-links-anchors-html-regular-expression-python.html
电话号码正则表达式：http://www.bogotobogo.com/python/python_regularExpressions.php
电话号码正则表达式：https://social.msdn.microsoft.com/Forums/en-US/6f63c479-a9f0-4d6b-a9ae-2ec2cea6e2b0/regular-expression-for-phone-number?forum=regexp
